apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
          env:
            - name: discovery.type
              value: single-node
            # Comprehensive JVM options to disable container detection and JMX
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m -XX:-UseContainerSupport -XX:+IgnoreUnrecognizedVMOptions -Djdk.attach.allowAttachSelf=true -Des.cgroups.enable=false -Dlog4j2.disable.jmx=true -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
            - name: xpack.security.enabled
              value: "false"
            # Additional environment variables to prevent cgroup issues
            - name: ES_TMPDIR
              value: /tmp
            - name: ELASTIC_CONTAINER
              value: "false"
          ports:
            - containerPort: 9200
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-storage
            - mountPath: /tmp
              name: tmp-volume
          # Security context with proper permissions
          securityContext:
            runAsNonRoot: false
            runAsUser: 1000
            fsGroup: 1000
            capabilities:
              drop:
                - ALL
      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200