apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      containers:
        - name: opensearch-dashboards
          image: opensearchproject/opensearch-dashboards:2.8.0
          env:
            - name: OPENSEARCH_HOSTS
              value: "http://opensearch:9200"
            - name: DISABLE_SECURITY_DASHBOARDS_PLUGIN
              value: "true"
          ports:
            - containerPort: 5601
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
  namespace: logging
spec:
  selector:
    app: opensearch-dashboards
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: NodePort